sudo: false
language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
install:
- pip install -U setuptools
- pip install -r requirements.txt #fix versions
- python setup.py develop
- pip install pytest pytest-cov coveralls #install test deps
script:
- py.test --cov skosprovider_getty --cov-report term-missing tests
after_success:
- coveralls
