sudo: false
language: python
os: linux
dist: focal
python:
- 3.8
- 3.9
- 3.10
install:
- pip install -U setuptools
- pip install -r requirements.txt #fix versions
- python setup.py develop
- pip install pytest pytest-cov coveralls #install test deps
script:
- py.test --cov skosprovider_getty --cov-report term-missing tests
after_success:
- coveralls
