sudo: false
language: python
os: linux
dist: focal
python:
- 3.9
- 3.10
- 3.11
install:
- pip install -U setuptools
- pip install -r requirements-dev.txt #fix versions
- python setup.py develop
script:
- py.test --cov skosprovider_getty --cov-report term-missing tests
after_success:
- coveralls
